### ISSUE TITLE
Document use cases

### ISSUE THREAD

**Issue by arnikz** [LINNAE-project/SFB-Annotator#1]
See an example [here](https://github.com/LINNAE-project/SFB-Annotator/blob/master/data/rdf/README.md).

**Comment by lisestork** [comment]
I wasn't sure if I was meant to work in branch dev, but I decided to make a branch with the issue number.  I've expanded the annotation of a taxon with all optionality. Working on the other annotatable classes atm.

**Comment by arnikz** [comment]
The numbering of examples went wrong as the `{2,3,4,5,6,7}_1` are not mentioned in the [README](https://github.com/LINNAE-project/SFB-Annotator/blob/master/data/rdf/README.md). I re-generated the RDF graphs (incl. ns prefixes; see #4) for each use case as is. Is the list of use cases complete? Then I'll proceed with renaming the files.

**Comment by lisestork** [comment]
The numbering of the examples was done like this on purpose, although maybe not the best choice. See the footnote * in the table, indicating that the `{2,3,4,5,6,7}_1` is similar for almost each case except for taxon and date. I think the rdf examples should still be generated, so maybe we can have them in the table anyway.

**Comment by lisestork** [comment]
I will add {2,3,4,5,6,7}_1 to the table & examples in the [README](../blob/master/data/rdf/README.md)

**Comment by arnikz** [comment]
Could you check if the query [JSON](https://github.com/LINNAE-project/SFB-Annotator/blob/iss4/data/rdf/example_1_1.json) strings (input) are in sync with the documented examples? It would be great if you could add the [cURL](https://github.com/LINNAE-project/SFB-Annotator/blob/iss4/data/rdf/curl.txt) commands (as copied e.g. from Firefox/Web Developer->Network->File->Copy->Copy as cURL using `Ctrl+Shift+I`) #4.

**Comment by arnikz** [comment]
In fact, the JSON files are the machine-readable version of the README, and are also used in the automated build (see #7).
