### ISSUE TITLE
Assign classes to IRIs referring to images

### ISSUE THREAD

**Issue by arnikz** [LINNAE-project/SFB-Annotator#16]
e.g.

`<http://makingsense.liacs.nl/rdf/nc/MMNAT01_AF_NNM001001033_003.jpg> a <http://purl.org/dc/dcmitype/Image>, <http://xmlns.com/foaf/spec/#term_Image> .`

**Comment by arnikz** [comment]
@lisestork: Is there something more specific e.g. in the NHC Ontology?

**Comment by lisestork** [comment]
[ncd](https://www.tdwg.org/standards/ncd/) but i'll look at it later

**Comment by arnikz** [comment]
replace `dcmitype:Image` with more specific `dcmtype:StillImage`
