### ISSUE TITLE
Existing annotations not shown in GUI

### ISSUE THREAD

**Issue by lisestork** [LINNAE-project/SFB-Annotator#2]
See https://github.com/LINNAE-project/SFB-Annotator/commit/3b0962179afd04af46872a366409659a2fbe330e

**Comment by lisestork** [comment]
Look at this [script](../blob/master/src/main/java/localdomain/localhost/servlets/loadAnnotations.java), annotations are loaded from the SQL db rather than RDF store

**Comment by arnikz** [comment]
![image](https://user-images.githubusercontent.com/7456848/113125231-afb8ed00-9216-11eb-9c0a-97b2f2cf74db.png)

**Comment by arnikz** [comment]
![image](https://user-images.githubusercontent.com/7456848/113702914-6ebf4d80-96da-11eb-8a4e-5f88fbb939bb.png)
