### ISSUE TITLE
Visualize RDF graphs per example input

### ISSUE THREAD

**Issue by lisestork** [LINNAE-project/SFB-Annotator#22]

**Comment by lisestork** [comment]
First version is online, [cyto-image](https://github.com/LINNAE-project/SFB-Annotator/blob/iss22/data/rdf/rdf_examples_low.png), still contains errors, and not clear enough which triples are generated when.

**Comment by arnikz** [comment]
Perhaps we could use [cytoscape.js](https://js.cytoscape.org/) to visualize RDF graphs (requires writing a custom module to transform data into JSON).

**Comment by lisestork** [comment]
> Perhaps we could use [cytoscape.js](https://js.cytoscape.org/) to visualize RDF graphs (requires writing a custom module to transform data into JSON).

Good idea, I'll look into it

**Comment by arnikz** [comment]
For each `example_*.json` (group minor numbered cases) generate RDF graphs in N-triples format.

**Comment by arnikz** [comment]
We could also make use of [this](https://github.com/candYgene/notebooks/blob/master/usecase_1/example_2/network_viz.ipynb) notebook to visualize the [RDF graphs](https://github.com/LINNAE-project/SFB-Annotator/tree/master/data/rdf) (Turtle).

**Comment by lisestork** [comment]
started altering visualisation jupyter notebook, in  [(https://github.com/LINNAE-project/SFB-Annotator/tree/iss22/visualisation)](https://github.com/LINNAE-project/SFB-Annotator/tree/iss22/visualisation)

**Comment by arnikz** [comment]
N.B. currently, the interactive viz. doesn't not support edge labels (predicates) so plot the example graphs in (static) SVG.
