### ISSUE TITLE
Explore the link between annotations and IIIF 

### ISSUE THREAD

**Issue by lisestork** [LINNAE-project/SFB-Annotator#23]

**Comment by arnikz** [comment]
See https://github.com/IIIF/awesome-iiif.

**Comment by lisestork** [comment]
[Tutorial](https://www.youtube.com/watch?v=XxHo5rbWehU), with IIIF and json (textual annotations, annotation lists). JSON-LD? Annotating with semantics? They mention linking to things (e.g. wikipedia) and using controlled vocabularies to tag annotations.

**Comment by arnikz** [comment]
Indeed, a very nice tutorial including some workshop materials [[1]](https://training.iiif.io/) [[2]](http://ronallo.com/iiif-workshop-new/). They show a (prototype) web app called [Mirador](https://projectmirador.org/), which makes use of Open/Web Annotation Data Model, RDFa/JSON-LD and (local) annotation store but would require further development for our use case(s) and production use.

**Comment by arnikz** [comment]
I think, we should adhere to the [IIIF spec](https://iiif.io/api/index.html) including the [architecture](https://training.iiif.io/intro-to-iiif/images/request_response.png). Moreover, the [IIIF context](https://iiif.io/api/presentation/3/context.json) includes OA, DC etc. For the simplest example, see the [Manifest](https://iiif.io/api/cookbook/recipe/0001-mvm-image/) (v3) of an image. Each file describes how to present a single object such as a book etc. Furthermore, the Annotorius/OpenSeadragon plugin (client-side) now includes support for [W3C Web Annotations](https://www.w3.org/TR/annotation-model/).

**Comment by lisestork** [comment]
a mirador example where an image has an sc:AnnotationList for both transcriptions and named entities. They label the lists with "label": "Transcription annotations", and "label": "Named Entity Extraction Annotations"). 

[demo link](https://presley.dlcs-ida.org/iiif/idatest01/_roll_M-1070_46_cvs-932-1132/manifest)

Example of transcription and named entity list of annotations: 

[transcriptions](https://transcriptions.dlcs-ida.org/annotations/line/?width=2128&canvas=https%3A%2F%2Fpresley.dlcs-ida.org%2Fiiif%2Fidatest01%2F_roll_M-1070_46_cvs-932-1132%2Fcanvas%2Fc938&image=https%3A%2F%2Fdlcs-ida.org%2Fiiif-img%2F2%2F1%2Fbf34e18c-6bf9-4e0f-b029-6718cdff93d3&height=3296), [named entities](https://annotations.dlcs-ida.org/annotationlist/2e76a8d10159fca064c265102c13dfb2/)

Example entity annotation (does not seem to use body?):

        {
            "@id": "https://elucidate.dlcs-ida.org/annotation/w3c/2e76a8d10159fca064c265102c13dfb2/1cc203d8-19ee-4ad3-ac08-3b3537e9569c",
            "@type": "oa:Annotation",
            "dcterms:created": {
                "@type": "xsd:dateTime",
                "@value": "2018-01-05T03:57:54.393Z"
            },
            "resource": [
                {
                    "@type": "oa:Tag",
                    "format": "text/plain",
                    "as:generator": {
                        "@id": "https://omeka.dlcs-ida.org/s/ida/montague/open"
                    },
                    "chars": "October,"
                },
                {
                    "format": "application/html",
                    "as:generator": {
                        "@id": "https://omeka.dlcs-ida.org/s/ida/montague/open/nlp/"
                    },
                    "chars": "<a href=\"https://omeka.dlcs-ida.org/s/ida/page/topics/virtual:date/october%2c\">https://omeka.dlcs-ida.org/s/ida/page/topics/virtual:date/october%2c</a>"
                },
                {
                    "as:generator": {
                        "@id": "https://omeka.dlcs-ida.org/s/ida/montague/open"
                    },
                    "@type": "oa:Tag",
                    "chars": "entity:DATE"
                }
            ],
            "on": "https://presley.dlcs-ida.org/iiif/idatest01/_roll_M-1070_46_cvs-932-1132/canvas/c938#xywh=523,1575,166,52",
            "motivation": "oa:tagging"
        },

**Comment by arnikz** [comment]
In fact, the `Annotation` examples above do not have `target` (mandatory) nor `body`.  Instead, check [this](https://iiif.io/api/cookbook/recipe/0001-mvm-image/manifest.json) MANIFEST (v3) in [Mirador](https://projectmirador.org/embed/?iiif-content=https://iiif.io/api/cookbook/recipe/0001-mvm-image/manifest.json).

```
$ curl https://iiif.io/api/cookbook/recipe/0001-mvm-image/manifest.json
{ 
  "@context": "http://iiif.io/api/presentation/3/context.json",
  "id": "https://iiif.io/api/cookbook/recipe/0001-mvm-image/manifest.json",
  "type": "Manifest",
  "label": {
    "en": [
      "Image 1"
    ]
  },
  "items": [
    {
      "id": "https://iiif.io/api/cookbook/recipe/0001-mvm-image/canvas/p1",
      "type": "Canvas",
      "height": 1800,
      "width": 1200,
      "items": [
        {
          "id": "https://iiif.io/api/cookbook/recipe/0001-mvm-image/page/p1/1",
          "type": "AnnotationPage",
          "items": [
            {
              "id": "https://iiif.io/api/cookbook/recipe/0001-mvm-image/annotation/p0001-image",
              "type": "Annotation",
              "motivation": "painting",
              "body": {
                "id": "http://iiif.io/api/presentation/2.1/example/fixtures/resources/page1-full.png",
                "type": "Image",
                "format": "image/png",
                "height": 1800,
                "width": 1200
              },
              "target": "https://iiif.io/api/cookbook/recipe/0001-mvm-image/canvas/p1"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by arnikz** [comment]
I took the liberty to rename this issue given the rage of topics discussed so far.
