### ISSUE TITLE
Replace instances of oa:TextualBody with blank nodes

### ISSUE THREAD

**Issue by arnikz** [LINNAE-project/SFB-Annotator#24]
For example, `<http://makingsense.liacs.nl/rdf/nc/textualBody1>` in
https://github.com/LINNAE-project/SFB-Annotator/blob/375b8c9ada105fde9a633c26f60dc394d7329161/data/rdf/example_1_1.ttl#L1-L6

https://github.com/LINNAE-project/SFB-Annotator/blob/375b8c9ada105fde9a633c26f60dc394d7329161/data/rdf/example_1_1.ttl#L15

See https://www.w3.org/TR/annotation-vocab/#textualbody.

**Comment by lisestork** [comment]
I will check the current data model for semantic tag replacement & IIIF

**Comment by arnikz** [comment]
> I will check the current data model for semantic tag replacement & IIIF

This is related to #25 and #26 instead.
