### ISSUE TITLE
Fix the generation of RDF triples

### ISSUE THREAD

**Issue by arnikz** [LINNAE-project/SFB-Annotator#4]
- [x] example 1_*
- [x] example 2_*
- [x] example 3_*
- [x] example 4_*
- [x] example 5_*
- [x] example 6_*
- [x] example 7_*

related to  #1

**Comment by arnikz** [comment]
@lisestork: Could you check if the query [JSON](https://github.com/LINNAE-project/SFB-Annotator/blob/iss4/data/rdf/example_1_1.json) strings (input) are in sync with the documented examples?

**Comment by lisestork** [comment]
As requested in [#1](../issues/1):
> Could you check if the query [JSON](https://github.com/LINNAE-project/SFB-Annotator/blob/iss4/data/json/example_1_1.json) strings (input) are in sync with the documented examples? It would be great if you could add the [cURL](https://github.com/LINNAE-project/SFB-Annotator/blob/iss4/data/json/curl.txt) commands (as copied e.g. from Firefox/Web Developer->Network->File->Copy->Copy as cURL using `Ctrl+Shift+I`) #4.

I'v added the cURL commands for the missing examples `{2,3,4,5,6,7}_1` and pushed to branch [#4](../tree/iss4/data/rdf/curl.txt), although they appear a bit different from yours.

 I've checked the [JSON](../blob/iss4/data/json/example_1_1.json) strings too. We should have a look at: 

1.  example [1_3.json](../blob/iss4/data/json/example_1_3.json) (prompt says 'occurrence ID' and json says 'identification ID'.). 

2. Maybe not relevant but for example  [3_2.json](../blob/iss4/data/json/example_3_2.json), the field gn:geonamesfeature IRI should have been left open as it is unknown. 

3. For example [4_2.json](../blob/iss4/data/json/example_4_2.json) the wrong property is selected. Should be `Identification based on (table)`: i've changed the [README](../blob/master/data/rdf/README.md) in [#4 ](../issues/1) to reflect this.

**Comment by arnikz** [comment]
> I'v added the cURL commands for the missing examples `{2,3,4,5,6,7}_1` and pushed to branch [#4](../tree/iss4/data/rdf/curl.txt), although they appear a bit different from yours.
> 
Fixed in b75f889c23d99996a5f1ae7ca8fbbb9496e444a2. Added missing JSON (7bafff0b005d9ce250ac95c74c1c8525a6a9cef2) and RDF/Turtle (1c10d2729d1068b0dcdb464e3005acbaeb08ddd1) files for the reference.

> I've checked the [JSON](../blob/iss4/data/rdf/example_1_1.json) strings too. We should have a look at:
> 
>     1. example [1_3.json](../blob/iss4/data/rdf/example_1_3.json) (prompt says 'occurrence ID' and json says 'identification ID'.).
> 
>     2. Maybe not relevant but for example  [3_2.json](../blob/iss4/data/rdf/example_3_2.json), the field gn:geonamesfeature IRI should have been left open as it is unknown.
> 
>     3. For example [4_2.json](../blob/iss4/data/rdf/example_4_2.json) the wrong property is selected. Should be `Identification based on (table)`: i've changed the [README](../blob/master/data/rdf/README.md) in [#4 ](../issues/1) to reflect this.

@lisestork: Could you fix the current [JSON files](https://github.com/LINNAE-project/SFB-Annotator/tree/iss4/data/json) accordingly?

**Comment by lisestork** [comment]
Can not find the data/rdf/urls.csv file, was it deleted? (updated by @arnikz in commit [b4166a](../commit/b4166a48425e48922a681b02b238f3bfc7f9307e))

**Comment by arnikz** [comment]
That's correct. It's not needed anymore. Moreover, those URLs included JSON data (these are now in request body).

**Comment by lisestork** [comment]
> @lisestork: Could you fix the current [JSON files](https://github.com/LINNAE-project/SFB-Annotator/tree/iss4/data/json) accordingly?

Fixed [3_2.json](../blob/iss4/data/json/example_3_2.json) and [4_2.json](../blob/iss4/data/json/example_4_2.json).
