### ISSUE TITLE
Incorrect ns prefix for scientificName* and taxonRank

### ISSUE THREAD

**Issue by arnikz** [LINNAE-project/SFB-Annotator#62]
`nhc` -> `dwc`

https://github.com/LINNAE-project/SFB-Annotator/blob/670a543addd5de9ca945bcd8281f584bd81776ea/data/rdf/local/example_1_1.ttl#L29

https://github.com/LINNAE-project/SFB-Annotator/blob/670a543addd5de9ca945bcd8281f584bd81776ea/data/rdf/local/example_1_2.ttl#L31

https://github.com/LINNAE-project/SFB-Annotator/blob/670a543addd5de9ca945bcd8281f584bd81776ea/data/rdf/local/example_2_2.ttl#L41

@lisestork: these dwc terms refer to properties (predicates); in the first two triples used incorrectly as objects. Instead, we could use terms from the [TAXRANK](https://www.ebi.ac.uk/ols/ontologies/taxrank) vocabulary. For example, https://identifiers.org/taxonomy:9397 refers to the [`order`](http://purl.obolibrary.org/obo/TAXRANK_0000003) of _Chiroptera_.

**Comment by lisestork** [comment]
> @lisestork: these dwc terms refer to properties (predicates); in the first two triples used incorrectly as objects. Instead, we could use terms from the TAXRANK vocabulary. For example, https://identifiers.org/taxonomy:9397 refers to the order of Chiroptera.

That's perfect. In some cases there was a somewhat distinct classification around 1820, but I think it is fair to say that these concepts have not changed significantly and can be used for our purpose.

**Comment by arnikz** [comment]
Also, the subject in the `<nc:taxon1>...` the last triple requires fixing.

**Comment by arnikz** [comment]
Replace [`dwc:scientificName`](http://rs.tdwg.org/dwc/terms/scientificName) with [`TAXRANK:0000006`](http://purl.obolibrary.org/obo/TAXRANK_0000006) (species).
