### ISSUE TITLE
nhc:additional* properties not defined by the NHC Ontology

### ISSUE THREAD

**Issue by arnikz** [LINNAE-project/SFB-Annotator#63]
See https://github.com/lisestork/NHC-Ontology/issues/6.

https://github.com/LINNAE-project/SFB-Annotator/blob/670a543addd5de9ca945bcd8281f584bd81776ea/data/rdf/local/example_1_3.ttl#L52

https://github.com/LINNAE-project/SFB-Annotator/blob/670a543addd5de9ca945bcd8281f584bd81776ea/data/rdf/local/example_1_3.ttl#L58

@lisestork: What about using [`dsw:hasIdentification`](http://purl.org/dsw/hasIdentification) (as in `example_1_2`) for time being?

**Comment by lisestork** [comment]
> @lisestork: What about using dsw:hasIdentification (as in example_1_2) for time being?

I agree, this complicates things and I agree we should keep things as simple as possible (we can revisit it later if necessary)
